### ISSUE TITLE
-std=c++11?

### ISSUE THREAD

**Issue by gophermmq** [Daffan/nav-competition-icra2022#1]
The setting in CMakeLists.txt is std=c++11, but I got compiling errors when building the package. According to the error message, I changed the setting to std=C++17. Would it be OK?

**Comment by Daffan** [comment]
Yes, I think so

**Comment by guichristmann** [comment]
+1. I also had to change to `-std=c++17` to get it to compile in Ubuntu 20.04 + Noetic. Suggest the maintainers update the `CMakeLists.txt`.
