### ISSUE TITLE
Gloal Plan only based on local costmap

### ISSUE THREAD

**Issue by sudo-Boris** [Daffan/nav-competition-icra2022#5]
Hi, I was wondering if the following is correct:
The move_base global plan only computes the global plan based on the local costmap, i. e. the walls visible and memorized through the Laser scan. Is this correct? There is no global map provided for the map_server node (if there was one).
Thank you in advance!

**Comment by Daffan** [comment]
Yes, global map is not available. Global map is computed by the local costmap.
